name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ released ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare version labels
        uses: k15g/action-version-labels@edge
        with:
          prefix: project

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: corretto
          cache: maven

      - name: Build
        run: make build

      - name: Upload artifact [target]
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target/*-shaded.jar
          if-no-files-found: error
          retention-days: 7

      - name: Lowercase github.repository
        run: echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      - name: Build and push Docker image [edge]
        if: !startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.vendor=Klakegg Consulting AS" \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:edge \
            --push .

      - name: Build and push Docker image [version]
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.vendor=Klakegg Consulting AS" \
            --label "org.opencontainers.image.version=${{ env.PROJECT_VERSION }}" \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:${{ env.PROJECT_VERSION }} \
            --push .

      - name: Build and push Docker image [latest]
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.vendor=Klakegg Consulting AS" \
            --label "org.opencontainers.image.version=${{ env.PROJECT_VERSION }}" \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:latest \
            --push .
